/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.38.1
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

export type { NftAbi } from './NftAbi';

export { NftAbi__factory } from './factories/NftAbi__factory';
