/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.47.0
  Forc version: 0.40.1
  Fuel-Core version: 0.19.0
*/

export type { NftAbi } from './NftAbi';

export { NftAbi__factory } from './factories/NftAbi__factory';
